# Generated by Django 5.0 on 2025-12-01 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("climate", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClimateRiskFactor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("community_id", models.CharField(max_length=20)),
                ("date", models.CharField(max_length=20)),
                ("annual_high_temp_days", models.IntegerField(blank=True, null=True)),
                ("flood_risk_score", models.FloatField(blank=True, null=True)),
                ("storm_risk_score", models.FloatField(blank=True, null=True)),
                ("heat_health_risk_coeff", models.FloatField(blank=True, null=True)),
            ],
            options={
                "db_table": "climate_risk_factor",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="CommunityGeo",
            fields=[
                (
                    "community_id",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("community_name", models.CharField(max_length=100)),
                ("longitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("borough", models.CharField(blank=True, max_length=100)),
                ("latitude", models.DecimalField(decimal_places=6, max_digits=9)),
            ],
            options={
                "db_table": "community_geo",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="HealthRiskResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("community_id", models.CharField(max_length=20)),
                ("date", models.CharField(max_length=20)),
                (
                    "comprehensive_risk_index",
                    models.IntegerField(blank=True, null=True),
                ),
                ("risk_level", models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                "db_table": "health_risk_result",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="WeatherObs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("community_id", models.CharField(max_length=20)),
                ("date", models.CharField(max_length=20)),
                ("PRCP", models.FloatField(blank=True, null=True)),
                ("SNOW", models.FloatField(blank=True, null=True)),
                ("SNWD", models.FloatField(blank=True, null=True)),
                ("TAVG", models.FloatField(blank=True, null=True)),
                ("TMAX", models.FloatField(blank=True, null=True)),
                ("TMIN", models.FloatField(blank=True, null=True)),
                ("TOBS", models.FloatField(blank=True, null=True)),
            ],
            options={
                "db_table": "weather_obs",
                "managed": False,
            },
        ),
    ]
