# Generated by Django 5.0 on 2025-12-01 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("climate", "0002_climateriskfactor_communitygeo_healthriskresult_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="climaterecord",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="climaterecord",
            name="community",
        ),
        migrations.DeleteModel(
            name="HealthRiskResult",
        ),
        migrations.DeleteModel(
            name="ClimateRecord",
        ),
        migrations.DeleteModel(
            name="Community",
        ),
    ]
